class Autogenerated {
  String name;
  String lastName;
  String profileImage;
  String createdAt;
  String updatedAt;
  bool state;
  String sId;
  int cin;
  int phone;
  String username;
  String email;
  String password;
  String role;
  int iV;

  Autogenerated(
      {this.name,
        this.lastName,
        this.profileImage,
        this.createdAt,
        this.updatedAt,
        this.state,
        this.sId,
        this.cin,
        this.phone,
        this.username,
        this.email,
        this.password,
        this.role,
        this.iV});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    name = json['name'];
    lastName = json['lastName'];
    profileImage = json['profileImage'];
    createdAt = json['createdAt'];
    updatedAt = json['updatedAt'];
    state = json['state'];
    sId = json['_id'];
    cin = json['cin'];
    phone = json['phone'];
    username = json['username'];
    email = json['email'];
    password = json['password'];
    role = json['role'];
    iV = json['__v'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['name'] = this.name;
    data['lastName'] = this.lastName;
    data['profileImage'] = this.profileImage;
    data['createdAt'] = this.createdAt;
    data['updatedAt'] = this.updatedAt;
    data['state'] = this.state;
    data['_id'] = this.sId;
    data['cin'] = this.cin;
    data['phone'] = this.phone;
    data['username'] = this.username;
    data['email'] = this.email;
    data['password'] = this.password;
    data['role'] = this.role;
    data['__v'] = this.iV;
    return data;
  }
}